import {
  School,
  Hostel,
  Classroom,
  WaterSource,
  PowerSource,
  HostelType,
  ConstructionType,
  Condition,
  OperationalStatus,
  WaterSourceType,
  WaterReliability,
  PowerSourceType,
} from "./types";

export const schools: School[] = [
  {
    id: "1",
    name: "Federal Government College, Lagos",
    state: "Lagos",
    totalStudents: 2450,
    totalStaff: 180,
    notes: "Well-maintained infrastructure with adequate capacity. All systems operational with regular maintenance schedules in place.",
    hostels: [
      {
        id: "h1",
        schoolId: "1",
        name: "Boys Hostel A",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2010,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 120,
        totalBeds: 480,
        currentOccupancy: 450,
      },
      {
        id: "h2",
        schoolId: "1",
        name: "Girls Hostel B",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2012,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 100,
        totalBeds: 400,
        currentOccupancy: 380,
      },
    ],
    classrooms: [
      {
        id: "c1",
        schoolId: "1",
        academicBlockName: "Main Block",
        seatingCapacity: 50,
        currentStudents: 45,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w1",
        schoolId: "1",
        sourceType: WaterSourceType.Borehole,
        capacity: 50000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-15",
      },
    ],
    powerSources: [
      {
        id: "p1",
        schoolId: "1",
        sourceType: PowerSourceType.Grid,
        capacity: 500,
        averageHoursPerDay: 20,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "2",
    name: "Federal Government College, Kaduna",
    state: "Kaduna",
    totalStudents: 3200,
    totalStaff: 220,
    notes: "Facing overcrowding challenges in hostels. Water supply is intermittent, requiring immediate attention. Power infrastructure is stable with backup generators.",
    hostels: [
      {
        id: "h3",
        schoolId: "2",
        name: "Boys Hostel Complex",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2005,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 150,
        totalBeds: 600,
        currentOccupancy: 750,
      },
      {
        id: "h4",
        schoolId: "2",
        name: "Girls Hostel Complex",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2005,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 140,
        totalBeds: 560,
        currentOccupancy: 680,
      },
    ],
    classrooms: [
      {
        id: "c2",
        schoolId: "2",
        academicBlockName: "Science Block",
        seatingCapacity: 40,
        currentStudents: 55,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w2",
        schoolId: "2",
        sourceType: WaterSourceType.Borehole,
        capacity: 30000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-11-20",
      },
    ],
    powerSources: [
      {
        id: "p2",
        schoolId: "2",
        sourceType: PowerSourceType.Generator,
        capacity: 300,
        averageHoursPerDay: 12,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "3",
    name: "Federal Government College, Enugu",
    state: "Enugu",
    totalStudents: 1800,
    totalStaff: 140,
    notes: "Critical infrastructure issues. Hostels in poor condition with structural concerns. Water supply unreliable. Urgent intervention required.",
    hostels: [
      {
        id: "h5",
        schoolId: "3",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1995,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 80,
        totalBeds: 320,
        currentOccupancy: 280,
      },
      {
        id: "h6",
        schoolId: "3",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1995,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 75,
        totalBeds: 300,
        currentOccupancy: 260,
      },
    ],
    classrooms: [
      {
        id: "c3",
        schoolId: "3",
        academicBlockName: "Main Block",
        seatingCapacity: 35,
        currentStudents: 42,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Poor,
      },
    ],
    waterSources: [
      {
        id: "w3",
        schoolId: "3",
        sourceType: WaterSourceType.Well,
        capacity: 15000,
        functionalStatus: false,
        reliability: WaterReliability.None,
        lastMaintenanceDate: "2022-08-10",
      },
    ],
    powerSources: [
      {
        id: "p3",
        schoolId: "3",
        sourceType: PowerSourceType.Generator,
        capacity: 200,
        averageHoursPerDay: 4,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
  },
  {
    id: "4",
    name: "Federal Government College, Abuja",
    state: "FCT",
    totalStudents: 2800,
    totalStaff: 200,
    notes: "Modern facilities with excellent infrastructure. All systems functioning optimally. Model school for other institutions.",
    hostels: [
      {
        id: "h7",
        schoolId: "4",
        name: "Boys Hostel North",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2018,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 140,
        totalBeds: 560,
        currentOccupancy: 520,
      },
      {
        id: "h8",
        schoolId: "4",
        name: "Girls Hostel South",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2018,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 130,
        totalBeds: 520,
        currentOccupancy: 480,
      },
    ],
    classrooms: [
      {
        id: "c4",
        schoolId: "4",
        academicBlockName: "Academic Complex",
        seatingCapacity: 45,
        currentStudents: 40,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w4",
        schoolId: "4",
        sourceType: WaterSourceType.Pipe,
        capacity: 75000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-02-01",
      },
    ],
    powerSources: [
      {
        id: "p4",
        schoolId: "4",
        sourceType: PowerSourceType.Grid,
        capacity: 600,
        averageHoursPerDay: 24,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "5",
    name: "Federal Government College, Ibadan",
    state: "Oyo",
    totalStudents: 2100,
    totalStaff: 160,
    notes: "Adequate infrastructure with minor maintenance needs. Water supply consistent. Power availability good with occasional grid interruptions.",
    hostels: [
      {
        id: "h9",
        schoolId: "5",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2008,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 110,
        totalBeds: 440,
        currentOccupancy: 420,
      },
      {
        id: "h10",
        schoolId: "5",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2008,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 105,
        totalBeds: 420,
        currentOccupancy: 400,
      },
    ],
    classrooms: [
      {
        id: "c5",
        schoolId: "5",
        academicBlockName: "Main Building",
        seatingCapacity: 42,
        currentStudents: 38,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w5",
        schoolId: "5",
        sourceType: WaterSourceType.Borehole,
        capacity: 40000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2023-12-05",
      },
    ],
    powerSources: [
      {
        id: "p5",
        schoolId: "5",
        sourceType: PowerSourceType.Grid,
        capacity: 400,
        averageHoursPerDay: 18,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "6",
    name: "Federal Government College, Kano",
    state: "Kano",
    totalStudents: 3500,
    totalStaff: 240,
    notes: "Severe overcrowding in hostels exceeding 130% capacity. Water infrastructure needs upgrade. Power supply adequate with backup systems.",
    hostels: [
      {
        id: "h11",
        schoolId: "6",
        name: "Boys Hostel East",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2000,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 180,
        totalBeds: 720,
        currentOccupancy: 950,
      },
      {
        id: "h12",
        schoolId: "6",
        name: "Girls Hostel West",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2000,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 170,
        totalBeds: 680,
        currentOccupancy: 880,
      },
    ],
    classrooms: [
      {
        id: "c6",
        schoolId: "6",
        academicBlockName: "Academic Block",
        seatingCapacity: 45,
        currentStudents: 60,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w6",
        schoolId: "6",
        sourceType: WaterSourceType.Borehole,
        capacity: 35000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-10-15",
      },
    ],
    powerSources: [
      {
        id: "p6",
        schoolId: "6",
        sourceType: PowerSourceType.Generator,
        capacity: 450,
        averageHoursPerDay: 16,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "7",
    name: "Federal Government College, Port Harcourt",
    state: "Rivers",
    totalStudents: 1950,
    totalStaff: 150,
    notes: "Infrastructure in fair condition. Water supply reliable. Power availability limited to 8 hours daily without adequate backup.",
    hostels: [
      {
        id: "h13",
        schoolId: "7",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2003,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 95,
        totalBeds: 380,
        currentOccupancy: 360,
      },
      {
        id: "h14",
        schoolId: "7",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2003,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 90,
        totalBeds: 360,
        currentOccupancy: 340,
      },
    ],
    classrooms: [
      {
        id: "c7",
        schoolId: "7",
        academicBlockName: "Main Block",
        seatingCapacity: 38,
        currentStudents: 35,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w7",
        schoolId: "7",
        sourceType: WaterSourceType.Pipe,
        capacity: 45000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-20",
      },
    ],
    powerSources: [
      {
        id: "p7",
        schoolId: "7",
        sourceType: PowerSourceType.Generator,
        capacity: 250,
        averageHoursPerDay: 8,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
  },
  {
    id: "8",
    name: "Federal Government College, Sokoto",
    state: "Sokoto",
    totalStudents: 1650,
    totalStaff: 130,
    notes: "Critical water shortage. No reliable water source functional. Hostel conditions deteriorating. Power supply minimal.",
    hostels: [
      {
        id: "h15",
        schoolId: "8",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1990,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 70,
        totalBeds: 280,
        currentOccupancy: 250,
      },
      {
        id: "h16",
        schoolId: "8",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1990,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 65,
        totalBeds: 260,
        currentOccupancy: 230,
      },
    ],
    classrooms: [
      {
        id: "c8",
        schoolId: "8",
        academicBlockName: "Academic Block",
        seatingCapacity: 32,
        currentStudents: 30,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Poor,
      },
    ],
    waterSources: [
      {
        id: "w8",
        schoolId: "8",
        sourceType: WaterSourceType.Well,
        capacity: 5000,
        functionalStatus: false,
        reliability: WaterReliability.None,
        lastMaintenanceDate: "2021-05-12",
      },
    ],
    powerSources: [
      {
        id: "p8",
        schoolId: "8",
        sourceType: PowerSourceType.Generator,
        capacity: 150,
        averageHoursPerDay: 5,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
  },
  {
    id: "9",
    name: "Federal Government College, Jos",
    state: "Plateau",
    totalStudents: 2200,
    totalStaff: 170,
    notes: "Good infrastructure overall. Minor overcrowding in some hostels. Water and power systems functioning well.",
    hostels: [
      {
        id: "h17",
        schoolId: "9",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2015,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 125,
        totalBeds: 500,
        currentOccupancy: 520,
      },
      {
        id: "h18",
        schoolId: "9",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2015,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 120,
        totalBeds: 480,
        currentOccupancy: 490,
      },
    ],
    classrooms: [
      {
        id: "c9",
        schoolId: "9",
        academicBlockName: "Main Building",
        seatingCapacity: 44,
        currentStudents: 42,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w9",
        schoolId: "9",
        sourceType: WaterSourceType.Borehole,
        capacity: 42000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-10",
      },
    ],
    powerSources: [
      {
        id: "p9",
        schoolId: "9",
        sourceType: PowerSourceType.Grid,
        capacity: 380,
        averageHoursPerDay: 19,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
  },
  {
    id: "10",
    name: "Federal Government College, Maiduguri",
    state: "Borno",
    totalStudents: 1400,
    totalStaff: 110,
    notes: "Infrastructure challenges due to security concerns. Limited power availability. Water supply functional but capacity constrained.",
    hostels: [
      {
        id: "h19",
        schoolId: "10",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2002,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 85,
        totalBeds: 340,
        currentOccupancy: 320,
      },
      {
        id: "h20",
        schoolId: "10",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2002,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 80,
        totalBeds: 320,
        currentOccupancy: 300,
      },
    ],
    classrooms: [
      {
        id: "c10",
        schoolId: "10",
        academicBlockName: "Academic Block",
        seatingCapacity: 35,
        currentStudents: 33,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w10",
        schoolId: "10",
        sourceType: WaterSourceType.Borehole,
        capacity: 25000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-09-18",
      },
    ],
    powerSources: [
      {
        id: "p10",
        schoolId: "10",
        sourceType: PowerSourceType.Generator,
        capacity: 180,
        averageHoursPerDay: 10,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
  },
];
