import {
  School,
  Hostel,
  Classroom,
  WaterSource,
  PowerSource,
  HostelType,
  ConstructionType,
  Condition,
  OperationalStatus,
  WaterSourceType,
  WaterReliability,
  PowerSourceType,
  EquipmentCategory,
  FacilityType,
} from "./types";

export const schools: School[] = [
  {
    id: "1",
    name: "Federal Government College, Lagos",
    state: "Lagos",
    totalStudents: 2450,
    totalStaff: 180,
    notes: "Well-maintained infrastructure with adequate capacity. All systems operational with regular maintenance schedules in place.",
    hostels: [
      {
        id: "h1",
        schoolId: "1",
        name: "Boys Hostel A",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2010,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 120,
        totalBeds: 480,
        currentOccupancy: 450,
      },
      {
        id: "h2",
        schoolId: "1",
        name: "Girls Hostel B",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2012,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 100,
        totalBeds: 400,
        currentOccupancy: 380,
      },
    ],
    classrooms: [
      {
        id: "c1",
        schoolId: "1",
        academicBlockName: "Main Block",
        seatingCapacity: 50,
        currentStudents: 45,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w1",
        schoolId: "1",
        sourceType: WaterSourceType.Borehole,
        capacity: 50000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-15",
      },
    ],
    powerSources: [
      {
        id: "p1",
        schoolId: "1",
        sourceType: PowerSourceType.Grid,
        capacity: 500,
        averageHoursPerDay: 20,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 145,
      qualified: 132,
      byQualification: { bEd: 95, mEd: 32, phd: 5, other: 13 },
      bySubjectArea: { science: 45, arts: 30, commercial: 25, technical: 15, languages: 12, mathematics: 10, socialStudies: 5, physicalEducation: 3 },
    },
    equipment: [
      { id: "e1", schoolId: "1", category: EquipmentCategory.Computers, totalCount: 120, functionalCount: 115, condition: Condition.Good },
      { id: "e2", schoolId: "1", category: EquipmentCategory.LabEquipment, totalCount: 85, functionalCount: 82, condition: Condition.Good },
      { id: "e3", schoolId: "1", category: EquipmentCategory.SportsEquipment, totalCount: 200, functionalCount: 195, condition: Condition.Good },
      { id: "e4", schoolId: "1", category: EquipmentCategory.Furniture, totalCount: 500, functionalCount: 485, condition: Condition.Good },
      { id: "e5", schoolId: "1", category: EquipmentCategory.LibraryBooks, totalCount: 15000, functionalCount: 15000, condition: Condition.Good },
    ],
    computerLabs: [
      { id: "cl1", schoolId: "1", name: "Main Computer Lab", totalComputers: 50, functionalComputers: 48, lastMaintenanceDate: "2024-01-15", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "cl2", schoolId: "1", name: "Secondary Computer Lab", totalComputers: 30, functionalComputers: 29, lastMaintenanceDate: "2024-01-10", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
    facilities: [
      { id: "f1", schoolId: "1", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 40, currentUsage: 38, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 25 },
      { id: "f2", schoolId: "1", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 40, currentUsage: 35, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 30 },
      { id: "f3", schoolId: "1", type: FacilityType.ScienceLab, name: "Biology Lab", capacity: 40, currentUsage: 36, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 28 },
      { id: "f4", schoolId: "1", type: FacilityType.Library, name: "Main Library", capacity: 200, currentUsage: 180, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 15000 },
      { id: "f5", schoolId: "1", type: FacilityType.SportsCenter, name: "Sports Complex", capacity: 500, currentUsage: 450, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f6", schoolId: "1", type: FacilityType.StaffQuarters, name: "Staff Quarters A", capacity: 60, currentUsage: 55, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f7", schoolId: "1", type: FacilityType.Auditorium, name: "Main Auditorium", capacity: 800, currentUsage: 750, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f8", schoolId: "1", type: FacilityType.Cafeteria, name: "Main Cafeteria", capacity: 400, currentUsage: 380, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "2",
    name: "Federal Government College, Kaduna",
    state: "Kaduna",
    totalStudents: 3200,
    totalStaff: 220,
    notes: "Facing overcrowding challenges in hostels. Water supply is intermittent, requiring immediate attention. Power infrastructure is stable with backup generators.",
    hostels: [
      {
        id: "h3",
        schoolId: "2",
        name: "Boys Hostel Complex",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2005,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 150,
        totalBeds: 600,
        currentOccupancy: 750,
      },
      {
        id: "h4",
        schoolId: "2",
        name: "Girls Hostel Complex",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2005,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 140,
        totalBeds: 560,
        currentOccupancy: 680,
      },
    ],
    classrooms: [
      {
        id: "c2",
        schoolId: "2",
        academicBlockName: "Science Block",
        seatingCapacity: 40,
        currentStudents: 55,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w2",
        schoolId: "2",
        sourceType: WaterSourceType.Borehole,
        capacity: 30000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-11-20",
      },
    ],
    powerSources: [
      {
        id: "p2",
        schoolId: "2",
        sourceType: PowerSourceType.Generator,
        capacity: 300,
        averageHoursPerDay: 12,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 195,
      qualified: 168,
      byQualification: { bEd: 140, mEd: 22, phd: 3, other: 30 },
      bySubjectArea: { science: 60, arts: 40, commercial: 35, technical: 20, languages: 18, mathematics: 15, socialStudies: 8, physicalEducation: 3 },
    },
    equipment: [
      { id: "e6", schoolId: "2", category: EquipmentCategory.Computers, totalCount: 80, functionalCount: 65, condition: Condition.Fair },
      { id: "e7", schoolId: "2", category: EquipmentCategory.LabEquipment, totalCount: 60, functionalCount: 45, condition: Condition.Fair },
      { id: "e8", schoolId: "2", category: EquipmentCategory.SportsEquipment, totalCount: 150, functionalCount: 120, condition: Condition.Fair },
      { id: "e9", schoolId: "2", category: EquipmentCategory.Furniture, totalCount: 400, functionalCount: 350, condition: Condition.Fair },
      { id: "e10", schoolId: "2", category: EquipmentCategory.LibraryBooks, totalCount: 12000, functionalCount: 11000, condition: Condition.Fair },
    ],
    computerLabs: [
      { id: "cl3", schoolId: "2", name: "Computer Lab 1", totalComputers: 35, functionalComputers: 28, lastMaintenanceDate: "2023-11-20", condition: Condition.Fair, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f9", schoolId: "2", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 50, currentUsage: 55, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 20 },
      { id: "f10", schoolId: "2", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 50, currentUsage: 52, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 22 },
      { id: "f11", schoolId: "2", type: FacilityType.Library, name: "Library", capacity: 250, currentUsage: 280, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 12000 },
      { id: "f12", schoolId: "2", type: FacilityType.SportsCenter, name: "Sports Center", capacity: 600, currentUsage: 650, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f13", schoolId: "2", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 80, currentUsage: 75, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f14", schoolId: "2", type: FacilityType.Auditorium, name: "Auditorium", capacity: 1000, currentUsage: 950, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f15", schoolId: "2", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 500, currentUsage: 520, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "3",
    name: "Federal Government College, Enugu",
    state: "Enugu",
    totalStudents: 1800,
    totalStaff: 140,
    notes: "Critical infrastructure issues. Hostels in poor condition with structural concerns. Water supply unreliable. Urgent intervention required.",
    hostels: [
      {
        id: "h5",
        schoolId: "3",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1995,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 80,
        totalBeds: 320,
        currentOccupancy: 280,
      },
      {
        id: "h6",
        schoolId: "3",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1995,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 75,
        totalBeds: 300,
        currentOccupancy: 260,
      },
    ],
    classrooms: [
      {
        id: "c3",
        schoolId: "3",
        academicBlockName: "Main Block",
        seatingCapacity: 35,
        currentStudents: 42,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Poor,
      },
    ],
    waterSources: [
      {
        id: "w3",
        schoolId: "3",
        sourceType: WaterSourceType.Well,
        capacity: 15000,
        functionalStatus: false,
        reliability: WaterReliability.None,
        lastMaintenanceDate: "2022-08-10",
      },
    ],
    powerSources: [
      {
        id: "p3",
        schoolId: "3",
        sourceType: PowerSourceType.Generator,
        capacity: 200,
        averageHoursPerDay: 4,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
    teacherSummary: {
      total: 110,
      qualified: 75,
      byQualification: { bEd: 60, mEd: 12, phd: 1, other: 37 },
      bySubjectArea: { science: 35, arts: 25, commercial: 20, technical: 10, languages: 8, mathematics: 7, socialStudies: 3, physicalEducation: 2 },
    },
    equipment: [
      { id: "e11", schoolId: "3", category: EquipmentCategory.Computers, totalCount: 40, functionalCount: 18, condition: Condition.Poor },
      { id: "e12", schoolId: "3", category: EquipmentCategory.LabEquipment, totalCount: 35, functionalCount: 12, condition: Condition.Poor },
      { id: "e13", schoolId: "3", category: EquipmentCategory.SportsEquipment, totalCount: 80, functionalCount: 45, condition: Condition.Poor },
      { id: "e14", schoolId: "3", category: EquipmentCategory.Furniture, totalCount: 250, functionalCount: 180, condition: Condition.Poor },
      { id: "e15", schoolId: "3", category: EquipmentCategory.LibraryBooks, totalCount: 8000, functionalCount: 6000, condition: Condition.Poor },
    ],
    computerLabs: [
      { id: "cl4", schoolId: "3", name: "Computer Lab", totalComputers: 20, functionalComputers: 8, lastMaintenanceDate: "2022-08-10", condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f16", schoolId: "3", type: FacilityType.ScienceLab, name: "Combined Science Lab", capacity: 30, currentUsage: 28, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial, equipmentCount: 10 },
      { id: "f17", schoolId: "3", type: FacilityType.Library, name: "Library", capacity: 150, currentUsage: 140, condition: Condition.Poor, operationalStatus: OperationalStatus.Functional, equipmentCount: 8000 },
      { id: "f18", schoolId: "3", type: FacilityType.SportsCenter, name: "Sports Field", capacity: 300, currentUsage: 280, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
      { id: "f19", schoolId: "3", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 40, currentUsage: 35, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
      { id: "f20", schoolId: "3", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 200, currentUsage: 180, condition: Condition.Poor, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "4",
    name: "Federal Government College, Abuja",
    state: "FCT",
    totalStudents: 2800,
    totalStaff: 200,
    notes: "Modern facilities with excellent infrastructure. All systems functioning optimally. Model school for other institutions.",
    hostels: [
      {
        id: "h7",
        schoolId: "4",
        name: "Boys Hostel North",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2018,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 140,
        totalBeds: 560,
        currentOccupancy: 520,
      },
      {
        id: "h8",
        schoolId: "4",
        name: "Girls Hostel South",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2018,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 130,
        totalBeds: 520,
        currentOccupancy: 480,
      },
    ],
    classrooms: [
      {
        id: "c4",
        schoolId: "4",
        academicBlockName: "Academic Complex",
        seatingCapacity: 45,
        currentStudents: 40,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w4",
        schoolId: "4",
        sourceType: WaterSourceType.Pipe,
        capacity: 75000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-02-01",
      },
    ],
    powerSources: [
      {
        id: "p4",
        schoolId: "4",
        sourceType: PowerSourceType.Grid,
        capacity: 600,
        averageHoursPerDay: 24,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 165,
      qualified: 158,
      byQualification: { bEd: 110, mEd: 40, phd: 8, other: 7 },
      bySubjectArea: { science: 50, arts: 35, commercial: 30, technical: 20, languages: 15, mathematics: 12, socialStudies: 2, physicalEducation: 1 },
    },
    equipment: [
      { id: "e16", schoolId: "4", category: EquipmentCategory.Computers, totalCount: 150, functionalCount: 148, condition: Condition.Good },
      { id: "e17", schoolId: "4", category: EquipmentCategory.LabEquipment, totalCount: 100, functionalCount: 98, condition: Condition.Good },
      { id: "e18", schoolId: "4", category: EquipmentCategory.SportsEquipment, totalCount: 250, functionalCount: 248, condition: Condition.Good },
      { id: "e19", schoolId: "4", category: EquipmentCategory.Furniture, totalCount: 600, functionalCount: 595, condition: Condition.Good },
      { id: "e20", schoolId: "4", category: EquipmentCategory.LibraryBooks, totalCount: 20000, functionalCount: 20000, condition: Condition.Good },
    ],
    computerLabs: [
      { id: "cl5", schoolId: "4", name: "Primary Computer Lab", totalComputers: 60, functionalComputers: 60, lastMaintenanceDate: "2024-02-01", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "cl6", schoolId: "4", name: "Secondary Computer Lab", totalComputers: 40, functionalComputers: 39, lastMaintenanceDate: "2024-01-25", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "cl7", schoolId: "4", name: "Advanced Computer Lab", totalComputers: 30, functionalComputers: 30, lastMaintenanceDate: "2024-02-05", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
    facilities: [
      { id: "f21", schoolId: "4", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 45, currentUsage: 42, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 35 },
      { id: "f22", schoolId: "4", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 45, currentUsage: 40, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 38 },
      { id: "f23", schoolId: "4", type: FacilityType.ScienceLab, name: "Biology Lab", capacity: 45, currentUsage: 43, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 32 },
      { id: "f24", schoolId: "4", type: FacilityType.Library, name: "Main Library", capacity: 250, currentUsage: 220, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 20000 },
      { id: "f25", schoolId: "4", type: FacilityType.SportsCenter, name: "Sports Complex", capacity: 600, currentUsage: 550, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f26", schoolId: "4", type: FacilityType.StaffQuarters, name: "Staff Quarters A", capacity: 70, currentUsage: 65, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f27", schoolId: "4", type: FacilityType.StaffQuarters, name: "Staff Quarters B", capacity: 50, currentUsage: 48, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f28", schoolId: "4", type: FacilityType.Auditorium, name: "Main Auditorium", capacity: 1000, currentUsage: 900, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f29", schoolId: "4", type: FacilityType.Cafeteria, name: "Main Cafeteria", capacity: 500, currentUsage: 450, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f30", schoolId: "4", type: FacilityType.Clinic, name: "Health Clinic", capacity: 20, currentUsage: 15, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "5",
    name: "Federal Government College, Ibadan",
    state: "Oyo",
    totalStudents: 2100,
    totalStaff: 160,
    notes: "Adequate infrastructure with minor maintenance needs. Water supply consistent. Power availability good with occasional grid interruptions.",
    hostels: [
      {
        id: "h9",
        schoolId: "5",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2008,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 110,
        totalBeds: 440,
        currentOccupancy: 420,
      },
      {
        id: "h10",
        schoolId: "5",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2008,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 105,
        totalBeds: 420,
        currentOccupancy: 400,
      },
    ],
    classrooms: [
      {
        id: "c5",
        schoolId: "5",
        academicBlockName: "Main Building",
        seatingCapacity: 42,
        currentStudents: 38,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w5",
        schoolId: "5",
        sourceType: WaterSourceType.Borehole,
        capacity: 40000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2023-12-05",
      },
    ],
    powerSources: [
      {
        id: "p5",
        schoolId: "5",
        sourceType: PowerSourceType.Grid,
        capacity: 400,
        averageHoursPerDay: 18,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 130,
      qualified: 118,
      byQualification: { bEd: 90, mEd: 25, phd: 3, other: 12 },
      bySubjectArea: { science: 40, arts: 28, commercial: 22, technical: 15, languages: 12, mathematics: 10, socialStudies: 2, physicalEducation: 1 },
    },
    equipment: [
      { id: "e21", schoolId: "5", category: EquipmentCategory.Computers, totalCount: 90, functionalCount: 85, condition: Condition.Good },
      { id: "e22", schoolId: "5", category: EquipmentCategory.LabEquipment, totalCount: 70, functionalCount: 68, condition: Condition.Good },
      { id: "e23", schoolId: "5", category: EquipmentCategory.SportsEquipment, totalCount: 180, functionalCount: 175, condition: Condition.Good },
      { id: "e24", schoolId: "5", category: EquipmentCategory.Furniture, totalCount: 450, functionalCount: 440, condition: Condition.Good },
      { id: "e25", schoolId: "5", category: EquipmentCategory.LibraryBooks, totalCount: 13000, functionalCount: 13000, condition: Condition.Good },
    ],
    computerLabs: [
      { id: "cl8", schoolId: "5", name: "Computer Lab", totalComputers: 45, functionalComputers: 43, lastMaintenanceDate: "2023-12-05", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
    facilities: [
      { id: "f31", schoolId: "5", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 40, currentUsage: 38, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 28 },
      { id: "f32", schoolId: "5", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 40, currentUsage: 36, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 30 },
      { id: "f33", schoolId: "5", type: FacilityType.Library, name: "Library", capacity: 200, currentUsage: 190, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 13000 },
      { id: "f34", schoolId: "5", type: FacilityType.SportsCenter, name: "Sports Center", capacity: 500, currentUsage: 480, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f35", schoolId: "5", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 55, currentUsage: 52, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f36", schoolId: "5", type: FacilityType.Auditorium, name: "Auditorium", capacity: 700, currentUsage: 650, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f37", schoolId: "5", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 350, currentUsage: 330, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "6",
    name: "Federal Government College, Kano",
    state: "Kano",
    totalStudents: 3500,
    totalStaff: 240,
    notes: "Severe overcrowding in hostels exceeding 130% capacity. Water infrastructure needs upgrade. Power supply adequate with backup systems.",
    hostels: [
      {
        id: "h11",
        schoolId: "6",
        name: "Boys Hostel East",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2000,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 180,
        totalBeds: 720,
        currentOccupancy: 950,
      },
      {
        id: "h12",
        schoolId: "6",
        name: "Girls Hostel West",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2000,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 170,
        totalBeds: 680,
        currentOccupancy: 880,
      },
    ],
    classrooms: [
      {
        id: "c6",
        schoolId: "6",
        academicBlockName: "Academic Block",
        seatingCapacity: 45,
        currentStudents: 60,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w6",
        schoolId: "6",
        sourceType: WaterSourceType.Borehole,
        capacity: 35000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-10-15",
      },
    ],
    powerSources: [
      {
        id: "p6",
        schoolId: "6",
        sourceType: PowerSourceType.Generator,
        capacity: 450,
        averageHoursPerDay: 16,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 210,
      qualified: 175,
      byQualification: { bEd: 150, mEd: 20, phd: 2, other: 38 },
      bySubjectArea: { science: 70, arts: 45, commercial: 40, technical: 25, languages: 15, mathematics: 12, socialStudies: 2, physicalEducation: 1 },
    },
    equipment: [
      { id: "e26", schoolId: "6", category: EquipmentCategory.Computers, totalCount: 100, functionalCount: 75, condition: Condition.Fair },
      { id: "e27", schoolId: "6", category: EquipmentCategory.LabEquipment, totalCount: 75, functionalCount: 55, condition: Condition.Fair },
      { id: "e28", schoolId: "6", category: EquipmentCategory.SportsEquipment, totalCount: 220, functionalCount: 180, condition: Condition.Fair },
      { id: "e29", schoolId: "6", category: EquipmentCategory.Furniture, totalCount: 550, functionalCount: 480, condition: Condition.Fair },
      { id: "e30", schoolId: "6", category: EquipmentCategory.LibraryBooks, totalCount: 14000, functionalCount: 12000, condition: Condition.Fair },
    ],
    computerLabs: [
      { id: "cl9", schoolId: "6", name: "Computer Lab 1", totalComputers: 50, functionalComputers: 38, lastMaintenanceDate: "2023-10-15", condition: Condition.Fair, operationalStatus: OperationalStatus.Partial },
      { id: "cl10", schoolId: "6", name: "Computer Lab 2", totalComputers: 30, functionalComputers: 22, lastMaintenanceDate: "2023-09-20", condition: Condition.Fair, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f38", schoolId: "6", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 60, currentUsage: 65, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 25 },
      { id: "f39", schoolId: "6", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 60, currentUsage: 68, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 28 },
      { id: "f40", schoolId: "6", type: FacilityType.ScienceLab, name: "Biology Lab", capacity: 60, currentUsage: 62, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 22 },
      { id: "f41", schoolId: "6", type: FacilityType.Library, name: "Library", capacity: 300, currentUsage: 320, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 14000 },
      { id: "f42", schoolId: "6", type: FacilityType.SportsCenter, name: "Sports Complex", capacity: 700, currentUsage: 750, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f43", schoolId: "6", type: FacilityType.StaffQuarters, name: "Staff Quarters A", capacity: 90, currentUsage: 85, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f44", schoolId: "6", type: FacilityType.Auditorium, name: "Main Auditorium", capacity: 1200, currentUsage: 1100, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f45", schoolId: "6", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 600, currentUsage: 650, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "7",
    name: "Federal Government College, Port Harcourt",
    state: "Rivers",
    totalStudents: 1950,
    totalStaff: 150,
    notes: "Infrastructure in fair condition. Water supply reliable. Power availability limited to 8 hours daily without adequate backup.",
    hostels: [
      {
        id: "h13",
        schoolId: "7",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2003,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 95,
        totalBeds: 380,
        currentOccupancy: 360,
      },
      {
        id: "h14",
        schoolId: "7",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2003,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 90,
        totalBeds: 360,
        currentOccupancy: 340,
      },
    ],
    classrooms: [
      {
        id: "c7",
        schoolId: "7",
        academicBlockName: "Main Block",
        seatingCapacity: 38,
        currentStudents: 35,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w7",
        schoolId: "7",
        sourceType: WaterSourceType.Pipe,
        capacity: 45000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-20",
      },
    ],
    powerSources: [
      {
        id: "p7",
        schoolId: "7",
        sourceType: PowerSourceType.Generator,
        capacity: 250,
        averageHoursPerDay: 8,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
    teacherSummary: {
      total: 120,
      qualified: 98,
      byQualification: { bEd: 75, mEd: 20, phd: 2, other: 23 },
      bySubjectArea: { science: 38, arts: 25, commercial: 22, technical: 12, languages: 10, mathematics: 9, socialStudies: 3, physicalEducation: 1 },
    },
    equipment: [
      { id: "e31", schoolId: "7", category: EquipmentCategory.Computers, totalCount: 70, functionalCount: 55, condition: Condition.Fair },
      { id: "e32", schoolId: "7", category: EquipmentCategory.LabEquipment, totalCount: 55, functionalCount: 42, condition: Condition.Fair },
      { id: "e33", schoolId: "7", category: EquipmentCategory.SportsEquipment, totalCount: 140, functionalCount: 115, condition: Condition.Fair },
      { id: "e34", schoolId: "7", category: EquipmentCategory.Furniture, totalCount: 380, functionalCount: 330, condition: Condition.Fair },
      { id: "e35", schoolId: "7", category: EquipmentCategory.LibraryBooks, totalCount: 11000, functionalCount: 10000, condition: Condition.Fair },
    ],
    computerLabs: [
      { id: "cl11", schoolId: "7", name: "Computer Lab", totalComputers: 35, functionalComputers: 28, lastMaintenanceDate: "2024-01-20", condition: Condition.Fair, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f46", schoolId: "7", type: FacilityType.ScienceLab, name: "Combined Science Lab", capacity: 35, currentUsage: 33, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 20 },
      { id: "f47", schoolId: "7", type: FacilityType.Library, name: "Library", capacity: 180, currentUsage: 170, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 11000 },
      { id: "f48", schoolId: "7", type: FacilityType.SportsCenter, name: "Sports Center", capacity: 400, currentUsage: 380, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f49", schoolId: "7", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 50, currentUsage: 45, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f50", schoolId: "7", type: FacilityType.Auditorium, name: "Auditorium", capacity: 600, currentUsage: 550, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f51", schoolId: "7", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 300, currentUsage: 280, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "8",
    name: "Federal Government College, Sokoto",
    state: "Sokoto",
    totalStudents: 1650,
    totalStaff: 130,
    notes: "Critical water shortage. No reliable water source functional. Hostel conditions deteriorating. Power supply minimal.",
    hostels: [
      {
        id: "h15",
        schoolId: "8",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1990,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 70,
        totalBeds: 280,
        currentOccupancy: 250,
      },
      {
        id: "h16",
        schoolId: "8",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Prefab,
        yearBuilt: 1990,
        condition: Condition.Poor,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 65,
        totalBeds: 260,
        currentOccupancy: 230,
      },
    ],
    classrooms: [
      {
        id: "c8",
        schoolId: "8",
        academicBlockName: "Academic Block",
        seatingCapacity: 32,
        currentStudents: 30,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: false,
        condition: Condition.Poor,
      },
    ],
    waterSources: [
      {
        id: "w8",
        schoolId: "8",
        sourceType: WaterSourceType.Well,
        capacity: 5000,
        functionalStatus: false,
        reliability: WaterReliability.None,
        lastMaintenanceDate: "2021-05-12",
      },
    ],
    powerSources: [
      {
        id: "p8",
        schoolId: "8",
        sourceType: PowerSourceType.Generator,
        capacity: 150,
        averageHoursPerDay: 5,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
    teacherSummary: {
      total: 88,
      qualified: 52,
      byQualification: { bEd: 40, mEd: 10, phd: 1, other: 37 },
      bySubjectArea: { science: 28, arts: 20, commercial: 15, technical: 8, languages: 7, mathematics: 6, socialStudies: 2, physicalEducation: 2 },
    },
    equipment: [
      { id: "e36", schoolId: "8", category: EquipmentCategory.Computers, totalCount: 30, functionalCount: 8, condition: Condition.Poor },
      { id: "e37", schoolId: "8", category: EquipmentCategory.LabEquipment, totalCount: 25, functionalCount: 6, condition: Condition.Poor },
      { id: "e38", schoolId: "8", category: EquipmentCategory.SportsEquipment, totalCount: 60, functionalCount: 25, condition: Condition.Poor },
      { id: "e39", schoolId: "8", category: EquipmentCategory.Furniture, totalCount: 200, functionalCount: 120, condition: Condition.Poor },
      { id: "e40", schoolId: "8", category: EquipmentCategory.LibraryBooks, totalCount: 6000, functionalCount: 4000, condition: Condition.Poor },
    ],
    computerLabs: [
      { id: "cl12", schoolId: "8", name: "Computer Lab", totalComputers: 15, functionalComputers: 4, lastMaintenanceDate: "2021-05-12", condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f52", schoolId: "8", type: FacilityType.ScienceLab, name: "Combined Lab", capacity: 25, currentUsage: 22, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial, equipmentCount: 8 },
      { id: "f53", schoolId: "8", type: FacilityType.Library, name: "Library", capacity: 120, currentUsage: 110, condition: Condition.Poor, operationalStatus: OperationalStatus.Functional, equipmentCount: 6000 },
      { id: "f54", schoolId: "8", type: FacilityType.SportsCenter, name: "Sports Field", capacity: 250, currentUsage: 230, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
      { id: "f55", schoolId: "8", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 35, currentUsage: 30, condition: Condition.Poor, operationalStatus: OperationalStatus.Partial },
      { id: "f56", schoolId: "8", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 150, currentUsage: 140, condition: Condition.Poor, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "9",
    name: "Federal Government College, Jos",
    state: "Plateau",
    totalStudents: 2200,
    totalStaff: 170,
    notes: "Good infrastructure overall. Minor overcrowding in some hostels. Water and power systems functioning well.",
    hostels: [
      {
        id: "h17",
        schoolId: "9",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2015,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 125,
        totalBeds: 500,
        currentOccupancy: 520,
      },
      {
        id: "h18",
        schoolId: "9",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Concrete,
        yearBuilt: 2015,
        condition: Condition.Good,
        operationalStatus: OperationalStatus.Functional,
        totalRooms: 120,
        totalBeds: 480,
        currentOccupancy: 490,
      },
    ],
    classrooms: [
      {
        id: "c9",
        schoolId: "9",
        academicBlockName: "Main Building",
        seatingCapacity: 44,
        currentStudents: 42,
        constructionType: ConstructionType.Concrete,
        ventilationAdequacy: true,
        condition: Condition.Good,
      },
    ],
    waterSources: [
      {
        id: "w9",
        schoolId: "9",
        sourceType: WaterSourceType.Borehole,
        capacity: 42000,
        functionalStatus: true,
        reliability: WaterReliability.Constant,
        lastMaintenanceDate: "2024-01-10",
      },
    ],
    powerSources: [
      {
        id: "p9",
        schoolId: "9",
        sourceType: PowerSourceType.Grid,
        capacity: 380,
        averageHoursPerDay: 19,
        operationalStatus: true,
        backupAvailable: true,
      },
    ],
    teacherSummary: {
      total: 135,
      qualified: 125,
      byQualification: { bEd: 95, mEd: 28, phd: 2, other: 10 },
      bySubjectArea: { science: 42, arts: 30, commercial: 25, technical: 15, languages: 12, mathematics: 10, socialStudies: 1, physicalEducation: 0 },
    },
    equipment: [
      { id: "e41", schoolId: "9", category: EquipmentCategory.Computers, totalCount: 95, functionalCount: 92, condition: Condition.Good },
      { id: "e42", schoolId: "9", category: EquipmentCategory.LabEquipment, totalCount: 75, functionalCount: 73, condition: Condition.Good },
      { id: "e43", schoolId: "9", category: EquipmentCategory.SportsEquipment, totalCount: 190, functionalCount: 185, condition: Condition.Good },
      { id: "e44", schoolId: "9", category: EquipmentCategory.Furniture, totalCount: 480, functionalCount: 470, condition: Condition.Good },
      { id: "e45", schoolId: "9", category: EquipmentCategory.LibraryBooks, totalCount: 13500, functionalCount: 13500, condition: Condition.Good },
    ],
    computerLabs: [
      { id: "cl13", schoolId: "9", name: "Computer Lab", totalComputers: 48, functionalComputers: 46, lastMaintenanceDate: "2024-01-10", condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
    facilities: [
      { id: "f57", schoolId: "9", type: FacilityType.ScienceLab, name: "Physics Lab", capacity: 42, currentUsage: 40, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 30 },
      { id: "f58", schoolId: "9", type: FacilityType.ScienceLab, name: "Chemistry Lab", capacity: 42, currentUsage: 38, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 32 },
      { id: "f59", schoolId: "9", type: FacilityType.Library, name: "Library", capacity: 220, currentUsage: 210, condition: Condition.Good, operationalStatus: OperationalStatus.Functional, equipmentCount: 13500 },
      { id: "f60", schoolId: "9", type: FacilityType.SportsCenter, name: "Sports Center", capacity: 550, currentUsage: 520, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f61", schoolId: "9", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 60, currentUsage: 58, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f62", schoolId: "9", type: FacilityType.Auditorium, name: "Auditorium", capacity: 800, currentUsage: 750, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
      { id: "f63", schoolId: "9", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 400, currentUsage: 380, condition: Condition.Good, operationalStatus: OperationalStatus.Functional },
    ],
  },
  {
    id: "10",
    name: "Federal Government College, Maiduguri",
    state: "Borno",
    totalStudents: 1400,
    totalStaff: 110,
    notes: "Infrastructure challenges due to security concerns. Limited power availability. Water supply functional but capacity constrained.",
    hostels: [
      {
        id: "h19",
        schoolId: "10",
        name: "Boys Hostel",
        type: HostelType.Male,
        constructionType: ConstructionType.Block,
        yearBuilt: 2002,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 85,
        totalBeds: 340,
        currentOccupancy: 320,
      },
      {
        id: "h20",
        schoolId: "10",
        name: "Girls Hostel",
        type: HostelType.Female,
        constructionType: ConstructionType.Block,
        yearBuilt: 2002,
        condition: Condition.Fair,
        operationalStatus: OperationalStatus.Partial,
        totalRooms: 80,
        totalBeds: 320,
        currentOccupancy: 300,
      },
    ],
    classrooms: [
      {
        id: "c10",
        schoolId: "10",
        academicBlockName: "Academic Block",
        seatingCapacity: 35,
        currentStudents: 33,
        constructionType: ConstructionType.Block,
        ventilationAdequacy: true,
        condition: Condition.Fair,
      },
    ],
    waterSources: [
      {
        id: "w10",
        schoolId: "10",
        sourceType: WaterSourceType.Borehole,
        capacity: 25000,
        functionalStatus: true,
        reliability: WaterReliability.Intermittent,
        lastMaintenanceDate: "2023-09-18",
      },
    ],
    powerSources: [
      {
        id: "p10",
        schoolId: "10",
        sourceType: PowerSourceType.Generator,
        capacity: 180,
        averageHoursPerDay: 10,
        operationalStatus: true,
        backupAvailable: false,
      },
    ],
    teacherSummary: {
      total: 88,
      qualified: 68,
      byQualification: { bEd: 55, mEd: 12, phd: 1, other: 20 },
      bySubjectArea: { science: 28, arts: 20, commercial: 15, technical: 10, languages: 8, mathematics: 7, socialStudies: 0, physicalEducation: 0 },
    },
    equipment: [
      { id: "e46", schoolId: "10", category: EquipmentCategory.Computers, totalCount: 55, functionalCount: 38, condition: Condition.Fair },
      { id: "e47", schoolId: "10", category: EquipmentCategory.LabEquipment, totalCount: 45, functionalCount: 32, condition: Condition.Fair },
      { id: "e48", schoolId: "10", category: EquipmentCategory.SportsEquipment, totalCount: 100, functionalCount: 75, condition: Condition.Fair },
      { id: "e49", schoolId: "10", category: EquipmentCategory.Furniture, totalCount: 320, functionalCount: 280, condition: Condition.Fair },
      { id: "e50", schoolId: "10", category: EquipmentCategory.LibraryBooks, totalCount: 9000, functionalCount: 7500, condition: Condition.Fair },
    ],
    computerLabs: [
      { id: "cl14", schoolId: "10", name: "Computer Lab", totalComputers: 28, functionalComputers: 20, lastMaintenanceDate: "2023-09-18", condition: Condition.Fair, operationalStatus: OperationalStatus.Partial },
    ],
    facilities: [
      { id: "f64", schoolId: "10", type: FacilityType.ScienceLab, name: "Combined Science Lab", capacity: 30, currentUsage: 28, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 18 },
      { id: "f65", schoolId: "10", type: FacilityType.Library, name: "Library", capacity: 150, currentUsage: 140, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional, equipmentCount: 9000 },
      { id: "f66", schoolId: "10", type: FacilityType.SportsCenter, name: "Sports Center", capacity: 350, currentUsage: 330, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f67", schoolId: "10", type: FacilityType.StaffQuarters, name: "Staff Quarters", capacity: 45, currentUsage: 42, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f68", schoolId: "10", type: FacilityType.Auditorium, name: "Auditorium", capacity: 500, currentUsage: 480, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
      { id: "f69", schoolId: "10", type: FacilityType.Cafeteria, name: "Cafeteria", capacity: 250, currentUsage: 230, condition: Condition.Fair, operationalStatus: OperationalStatus.Functional },
    ],
  },
];
